//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebXemPhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        public int IDBL { get; set; }
        public int IDPhim { get; set; }
        public int IDND { get; set; }
        public string NDBL { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual Phim Phim { get; set; }
    }
}
