//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebXemPhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phim()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
        }
    
        public int IDPhim { get; set; }
        public string TenPhim { get; set; }
        public string DaoDien { get; set; }
        public int IDQG { get; set; }
        public Nullable<int> NamSX { get; set; }
        public string ThoiLuong { get; set; }
        public string ChatLuong { get; set; }
        public string NgonNgu { get; set; }
        public string TheLoai { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public string MoTa { get; set; }
        public string LinkPhim { get; set; }
        public string LinkAnh { get; set; }
        public Nullable<int> Tap { get; set; }
        public int IDBo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        public virtual Bo Bo { get; set; }
        public virtual QuocGia QuocGia { get; set; }
    }
}
